[build]
  publish = "build"
  command = "npm run webpack --mode=production"
  functions = "lambda"
[build.environment]
  NODE_VERSION = "12.16.2"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"
